// swift-tools-version: 6.2

// `sevo` — the CLI + MCP server. One executable
// target that compiles the CLI sources in Sevo/ together with the app's own
// shared source files (lifecycle, CDP client, detections), so the CLI and the
// app cannot drift: same files, two build products. The app itself still
// builds from Sevoflurane.xcodeproj; this package is only how `sevo` builds.
import Foundation
import PackageDescription

/// Working notes sit beside the sources on a development machine and are
/// gitignored, so a clone has none of them. SwiftPM warns about an exclude
/// that names nothing, so only what is present is listed.
let packageContents = (try? FileManager.default.contentsOfDirectory(atPath: Context.packageDirectory)) ?? []
let localOnly = ["DELETE-CANDIDATES.md", "Docs", "HANDOFF.md", "Mockups", "Spike", "default.profraw"]
    .filter(packageContents.contains)

let package = Package(
    name: "sevo",
    platforms: [.macOS("26.0")],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.5.0"),
    ],
    targets: [
        .executableTarget(
            name: "sevo",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: ".",
            // Everything in the repo that is not one of `sources` below.
            exclude: localOnly + [
                "CONTRIBUTING.md",
                "LICENSE",
                "README.md",
                "Sevoflurane.xcodeproj",
                "Sevoflurane/App",
                "Sevoflurane/Assets.xcassets",
                "Sevoflurane/Bridge/BridgeJS.swift",
                "Sevoflurane/Bridge/HTTPServer.swift",
                "Sevoflurane/Bridge/LoopbackAssets.swift",
                "Sevoflurane/Bridge/SteamBridge.swift",
                "Sevoflurane/Bridge/WebProxy.swift",
                "Sevoflurane/Bridge/WebSocketServer.swift",
                "Sevoflurane/Bridge/steamclient_shim.js",
                "Sevoflurane/Info.plist",
                "Sevoflurane/Resources",
                "Sevoflurane/Setup/EngineFilePanel.swift",
                "Sevoflurane/Setup/GPTkDownload.swift",
                "Sevoflurane/Setup/GPTkDownloadPanel.swift",
                "Sevoflurane/Setup/SetupDryRun.swift",
                "Sevoflurane/Setup/SetupView.swift",
                "Sevoflurane/Sevoflurane.icon",
                "Sevoflurane/Support/AgentIntegration.swift",
                "Sevoflurane/Support/MainThreadHop.swift",
                "Sevoflurane/Support/MainQueueLatencyProbe.swift",
                "Sevoflurane/Support/MenuTrackingWatchdog.swift",
                "Sevoflurane/Support/SteamScreenSpace.swift",
                "Sevoflurane/Support/SyntheticLoad.swift",
                "Sevoflurane/Support/WineChronicle.swift",
                "Sevoflurane/Support/WineWindowWatch.swift",
                "Sevoflurane/Web",
                "SevofluraneDaemon",
                "SevofluraneTests",
                "SevofluraneThumbnail",
                "Tools",
            ],
            sources: [
                "Sevo",
                "Shared",
                "Sevoflurane/Bridge/CDPClient.swift",
                "Sevoflurane/Setup/D3DMetalInstaller.swift",
                "Sevoflurane/Setup/EngineInstaller.swift",
                "Sevoflurane/Setup/EngineManifest.swift",
                "Sevoflurane/Setup/EngineSignature.swift",
                "Sevoflurane/Setup/Provisioner.swift",
                "Sevoflurane/Setup/SetupEnvironment.swift",
                "Sevoflurane/Setup/SetupLog.swift",
                "Sevoflurane/Setup/SetupDetection.swift",
                "Sevoflurane/Support/AdoptedPrograms.swift",
                "Sevoflurane/Support/BottleDependencies.swift",
                "Sevoflurane/Support/BottleGraphics.swift",
                "Sevoflurane/Support/BottleOwner.swift",
                "Sevoflurane/Support/BottleReadiness.swift",
                "Sevoflurane/Support/BridgePorts.swift",
                "Sevoflurane/Support/BundledResources.swift",
                "Sevoflurane/Support/CDPBudget.swift",
                "Sevoflurane/Support/ClientLifecycle.swift",
                "Sevoflurane/Support/ConfigMaterializer.swift",
                "Sevoflurane/Support/CrossOverShadow.swift",
                "Sevoflurane/Support/Deadline.swift",
                "Sevoflurane/Support/DebugMode.swift",
                "Sevoflurane/Support/DiscordApplications.swift",
                "Sevoflurane/Support/DiscordPresence.swift",
                "Sevoflurane/Support/Engine.swift",
                "Sevoflurane/Support/EngineRenderers.swift",
                "Sevoflurane/Support/FileDigest.swift",
                "Sevoflurane/Support/GPUEquivalence.swift",
                "Sevoflurane/Support/GPUIdentity.swift",
                "Sevoflurane/Support/GameAttribution.swift",
                "Sevoflurane/Support/GameCompat.swift",
                "Sevoflurane/Support/GameCompatService.swift",
                "Sevoflurane/Support/GameConfig.swift",
                "Sevoflurane/Support/GameExecutables.swift",
                "Sevoflurane/Support/GameIcon.swift",
                "Sevoflurane/Support/GameLogs.swift",
                "Sevoflurane/Support/GameLaunchers.swift",
                "Sevoflurane/Support/HostSnapshot.swift",
                "Sevoflurane/Support/InstallDirectory.swift",
                "Sevoflurane/Support/JSLiteral.swift",
                "Sevoflurane/Support/KnownFailures.swift",
                "Sevoflurane/Support/NWJSGames.swift",
                "Sevoflurane/Support/NWJSRunner.swift",
                "Sevoflurane/Support/NWJSRuntime.swift",
                "Sevoflurane/Support/PerformanceProbes.swift",
                "Sevoflurane/Support/PopupSweeper.swift",
                "Sevoflurane/Support/Preferences.swift",
                "Sevoflurane/Support/PresentStats.swift",
                "Sevoflurane/Support/ProgramDetection.swift",
                "Sevoflurane/Support/Redaction.swift",
                "Sevoflurane/Support/RendererVersions.swift",
                "Sevoflurane/Support/RunRecorder.swift",
                "Sevoflurane/Support/ShaderPackages.swift",
                "Sevoflurane/Support/SharedGames.swift",
                "Sevoflurane/Support/SteamBottle.swift",
                "Sevoflurane/Support/SteamChatAutoOpen.swift",
                "Sevoflurane/Support/SteamMessageSound.swift",
                "Sevoflurane/Support/StorageInventory.swift",
                "Sevoflurane/Support/SteamWebCookie.swift",
                "Sevoflurane/Support/Subprocess.swift",
                "Sevoflurane/Support/SupervisorLink.swift",
                "Sevoflurane/Support/SupervisorState.swift",
                "Sevoflurane/Support/WineLog.swift",
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6),
                .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
            ],
        ),
    ],
)
